#ifndef NIMERA_ABI_SYSCALL_H
#define NIMERA_ABI_SYSCALL_H

/* Nimera v0 syscall ABI: number in x8, arguments in x0-x5, result in x0. */
#define NIMERA_SYS_WRITE_CONSOLE 1
#define NIMERA_SYS_EXIT 2
#define NIMERA_SYS_OPEN 3
#define NIMERA_SYS_READ 4
#define NIMERA_SYS_WRITE 5
#define NIMERA_SYS_CLOSE 6
#define NIMERA_SYS_TERM_READ_KEY 7
#define NIMERA_SYS_TERM_GET_SIZE 8
#define NIMERA_SYS_TERM_CLEAR 9
#define NIMERA_SYS_TERM_MOVE_CURSOR 10
#define NIMERA_SYS_TERM_CLEAR_LINE 11
#define NIMERA_SYS_TERM_SET_CURSOR_VISIBLE 12
#define NIMERA_SYS_MEM_ALLOC 13
#define NIMERA_SYS_MEM_FREE 14

#define NIMERA_OPEN_READ 0x01ULL
#define NIMERA_OPEN_WRITE 0x02ULL
#define NIMERA_OPEN_CREATE 0x04ULL
#define NIMERA_OPEN_TRUNCATE 0x08ULL
#define NIMERA_OPEN_APPEND 0x10ULL

#define NIMERA_NERR_INVALID (-1LL)
#define NIMERA_NERR_NOT_FOUND (-2LL)
#define NIMERA_NERR_ACCESS (-3LL)
#define NIMERA_NERR_NO_MEMORY (-4LL)
#define NIMERA_NERR_NO_HANDLES (-5LL)
#define NIMERA_NERR_IO (-6LL)
#define NIMERA_NERR_IS_DIRECTORY (-7LL)
#define NIMERA_NERR_BAD_HANDLE (-8LL)
#define NIMERA_NERR_TOO_LARGE (-9LL)

#endif
